CLASS zcl_07_leon_jpf DEFINITION INHERITING FROM zcl_06_animal_jpf

  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_07_leon_jpf IMPLEMENTATION.
  METHOD walk.
rv_walk = 'El león anda'.
  ENDMETHOD.

ENDCLASS.
