CLASS zcl_herencia3_class_jpf DEFINITION INHERITING FROM zcl_herencia2_class_jpf
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_herencia3_class_jpf IMPLEMENTATION.
ENDCLASS.
